// Code generated by goctl. DO NOT EDIT.
package types

type WebhookRequest struct {
	BotId int64 `path:"botId"`
}

type PayNotifyBody struct {
	TradeId            string  `json:"trade_id"`
	OrderId            string  `json:"order_id"`
	Amount             float64 `json:"amount"`
	ActualAmount       float64 `json:"actual_amount"`
	Token              string  `json:"token"`
	BlockTransactionId string  `json:"block_transaction_id"`
	Signature          string  `json:"signature"`
	Status             int     `json:"status"`
}

type PayNotifyRequest struct {
	Type string `path:"type"`
	PayNotifyBody
}
