// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/buyaobilian1/autobuytgvip-saas/btp-saas/internal/svc"
	"github.com/zeromicro/go-zero/rest"
	"net/http"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/webhook/:botId",
				Handler: WebhookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pay/notify/:type",
				Handler: PayNotifyHandler(serverCtx),
			},
		},
	)
}
