// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecharge = "recharge"

// Recharge mapped from table <recharge>
type Recharge struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int32     `gorm:"column:user_id;not null;comment:user id" json:"user_id"`                      // user id
	BotID        int64     `gorm:"column:bot_id;not null;comment:机器人id" json:"bot_id"`                          // 机器人id
	OrderNo      string    `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`                        // 订单号
	Amount       float64   `gorm:"column:amount;not null;comment:需支付USDT数" json:"amount"`                       // 需支付USDT数
	Status       int32     `gorm:"column:status;not null;default:1;comment:1：等待支付，2：支付成功，3：过期作废" json:"status"` // 1：等待支付，2：支付成功，3：过期作废
	ActualAmount float64   `gorm:"column:actual_amount;not null;comment:实际支付金额，由支付平台返回" json:"actual_amount"`   // 实际支付金额，由支付平台返回
	CreatedAt    time.Time `gorm:"column:created_at;not null;comment:订单创建时间" json:"created_at"`                 // 订单创建时间
	TgChatID     int64     `gorm:"column:tg_chat_id;not null" json:"tg_chat_id"`
	TgMsgID      int32     `gorm:"column:tg_msg_id;not null" json:"tg_msg_id"`
}

// TableName Recharge's table name
func (*Recharge) TableName() string {
	return TableNameRecharge
}
