// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWithdraw = "withdraw"

// Withdraw mapped from table <withdraw>
type Withdraw struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`
	TgID      int64     `gorm:"column:tg_id;not null" json:"tg_id"`
	OrderNo   string    `gorm:"column:order_no;not null;comment:提现订单号" json:"order_no"`            // 提现订单号
	Amount    float64   `gorm:"column:amount;not null;comment:提现金额" json:"amount"`                 // 提现金额
	TronAddr  string    `gorm:"column:tron_addr;not null;comment:提现钱包" json:"tron_addr"`           // 提现钱包
	Status    int32     `gorm:"column:status;not null;comment:1：等待提现，2：提现完成，3：提现失败" json:"status"` // 1：等待提现，2：提现完成，3：提现失败
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Withdraw's table name
func (*Withdraw) TableName() string {
	return TableNameWithdraw
}
