// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID            int32     `gorm:"column:user_id;not null;comment:买家user id" json:"user_id"`                             // 买家user id
	AgentUserID       int32     `gorm:"column:agent_user_id;not null;comment:下单时机器人所属代理user id，机器人可能更换" json:"agent_user_id"` // 下单时机器人所属代理user id，机器人可能更换
	BotID             int64     `gorm:"column:bot_id;not null;comment:机器人id" json:"bot_id"`                                   // 机器人id
	OrderNo           string    `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`                                 // 订单号
	FragmentRefID     *string   `gorm:"column:fragment_ref_id;comment:与fragment对应的ref" json:"fragment_ref_id"`                // 与fragment对应的ref
	ReceiveTgUsername string    `gorm:"column:receive_tg_username;not null;comment:接收会员的tg用户名" json:"receive_tg_username"`    // 接收会员的tg用户名
	VipMonth          int32     `gorm:"column:vip_month;not null;comment:开通vip时长3、6、12" json:"vip_month"`                     // 开通vip时长3、6、12
	UsdtAmount        float64   `gorm:"column:usdt_amount;not null;comment:需支付USDT数" json:"usdt_amount"`                      // 需支付USDT数
	BaseAmount        float64   `gorm:"column:base_amount;not null;comment:给到代理的价格" json:"base_amount"`                       // 给到代理的价格
	Status            int32     `gorm:"column:status;not null;default:1;comment:1：等待支付，2：支付成功，3：开通成功，4：过期作废" json:"status"`   // 1：等待支付，2：支付成功，3：开通成功，4：过期作废
	AgentStatus       int32     `gorm:"column:agent_status;not null;default:1;comment:1：等待入账，2：代理已入账" json:"agent_status"`    // 1：等待入账，2：代理已入账
	CreatedAt         time.Time `gorm:"column:created_at;not null;comment:订单创建时间" json:"created_at"`                          // 订单创建时间
	ExpiredAt         time.Time `gorm:"column:expired_at;not null;comment:订单过期时间" json:"expired_at"`                          // 订单过期时间
	TgChatID          int64     `gorm:"column:tg_chat_id;not null" json:"tg_chat_id"`
	TgMsgID           int32     `gorm:"column:tg_msg_id;not null" json:"tg_msg_id"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
