// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID               int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID         int32      `gorm:"column:parent_id;not null;comment:上级用户id，从哪个用户的机器人进来的" json:"parent_id"`            // 上级用户id，从哪个用户的机器人进来的
	TgID             int64      `gorm:"column:tg_id;not null;comment:tg id" json:"tg_id"`                                  // tg id
	TgUsername       *string    `gorm:"column:tg_username;comment:tg username" json:"tg_username"`                         // tg username
	Balance          float64    `gorm:"column:balance;not null;default:0.00;comment:USDT钱包" json:"balance"`                // USDT钱包
	Brokerage        float64    `gorm:"column:brokerage;not null;default:0.00;comment:代理佣金" json:"brokerage"`              // 代理佣金
	TronAddr         *string    `gorm:"column:tron_addr;comment:USDT收款钱包地址" json:"tron_addr"`                              // USDT收款钱包地址
	CreatedAt        time.Time  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                         // 创建时间
	BotID            *int64     `gorm:"column:bot_id;comment:机器人id" json:"bot_id"`                                         // 机器人id
	BotToken         *string    `gorm:"column:bot_token;comment:机器人token" json:"bot_token"`                                // 机器人token
	BotUsername      *string    `gorm:"column:bot_username;comment:机器人username" json:"bot_username"`                       // 机器人username
	BotStatus        int32      `gorm:"column:bot_status;not null;default:1;comment:1：正常，2：无，3：异常，4：禁用" json:"bot_status"` // 1：正常，2：无，3：异常，4：禁用
	BotCreatedAt     *time.Time `gorm:"column:bot_created_at;comment:机器人添加时间" json:"bot_created_at"`                       // 机器人添加时间
	ThreeMonthPrice  *float64   `gorm:"column:three_month_price;comment:三个月套餐价格" json:"three_month_price"`                 // 三个月套餐价格
	SixMonthPrice    *float64   `gorm:"column:six_month_price;comment:六个月套餐价格" json:"six_month_price"`                     // 六个月套餐价格
	TwelveMonthPrice *float64   `gorm:"column:twelve_month_price;comment:一年套餐价格" json:"twelve_month_price"`                // 一年套餐价格
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
